const DOMAIN_SLUG_MAP: Record<string, string> = {
  "github.com": "github",
  "gitlab.com": "gitlab",
  "bitbucket.org": "bitbucket",
  "youtube.com": "youtube",
  "youtu.be": "youtube",
  "reddit.com": "reddit",
  "twitter.com": "x",
  "x.com": "x",
  "facebook.com": "facebook",
  "instagram.com": "instagram",
  "linkedin.com": "linkedin",
  "discord.com": "discord",
  "discord.gg": "discord",
  "slack.com": "slack",
  "trello.com": "trello",
  "notion.so": "notion",
  "notion.site": "notion",
  "figma.com": "figma",
  "dribbble.com": "dribbble",
  "behance.net": "behance",
  "medium.com": "medium",
  "dev.to": "devdotto",
  "stackoverflow.com": "stackoverflow",
  "stackexchange.com": "stackexchange",
  "wikipedia.org": "wikipedia",
  "amazon.com": "amazon",
  "amazon.de": "amazon",
  "amazon.co.uk": "amazon",
  "netflix.com": "netflix",
  "spotify.com": "spotify",
  "apple.com": "apple",
  "microsoft.com": "microsoft",
  "google.com": "google",
  "drive.google.com": "googledrive",
  "mail.google.com": "gmail",
  "docs.google.com": "googledocs",
  "calendar.google.com": "googlecalendar",
  "maps.google.com": "googlemaps",
  "cloudflare.com": "cloudflare",
  "vercel.com": "vercel",
  "digitalocean.com": "digitalocean",
  "aws.amazon.com": "amazonaws",
  "pypi.org": "python",
  "npmjs.com": "npmjs",
  "docker.com": "docker",
  "plex.tv": "plex",
  "sonarr.tv": "sonarr",
  "radarr.video": "radarr",
  "jellyfin.org": "jellyfin",
  "pi-hole.net": "pihole",
  "portainer.io": "portainer",
  "proxmox.com": "proxmox",
  "traefik.io": "traefikproxy",
  "nextcloud.com": "nextcloud",
  "home-assistant.io": "homeassistant",
  "grafana.com": "grafana",
  "prometheus.io": "prometheus",
  "jira.com": "jira",
  "confluence.com": "confluence",
  "linear.app": "linear",
  "railway.app": "railway",
  "supabase.com": "supabase",
  "stripe.com": "stripe",
  "paypal.com": "paypal",
};

export function getSimpleIconUrl(slug: string, color?: string): string {
  const base = `https://cdn.simpleicons.org/${slug}`;
  return color ? `${base}/${color}` : base;
}

export function getSlugForDomain(domain: string): string | null {
  return DOMAIN_SLUG_MAP[domain.toLowerCase()] ?? null;
}

export function getSlugForUrl(url: string): string | null {
  try {
    const hostname = new URL(url).hostname.toLowerCase();
    return getSlugForDomain(hostname);
  } catch {
    return null;
  }
}

export const SEARCHABLE_ICONS: Array<{ slug: string; name: string }> = [
  { slug: "github", name: "GitHub" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "bitbucket", name: "Bitbucket" },
  { slug: "youtube", name: "YouTube" },
  { slug: "reddit", name: "Reddit" },
  { slug: "x", name: "X (Twitter)" },
  { slug: "facebook", name: "Facebook" },
  { slug: "instagram", name: "Instagram" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "discord", name: "Discord" },
  { slug: "slack", name: "Slack" },
  { slug: "trello", name: "Trello" },
  { slug: "notion", name: "Notion" },
  { slug: "figma", name: "Figma" },
  { slug: "dribbble", name: "Dribbble" },
  { slug: "behance", name: "Behance" },
  { slug: "medium", name: "Medium" },
  { slug: "devdotto", name: "Dev.to" },
  { slug: "stackoverflow", name: "Stack Overflow" },
  { slug: "wikipedia", name: "Wikipedia" },
  { slug: "amazon", name: "Amazon" },
  { slug: "netflix", name: "Netflix" },
  { slug: "spotify", name: "Spotify" },
  { slug: "apple", name: "Apple" },
  { slug: "microsoft", name: "Microsoft" },
  { slug: "google", name: "Google" },
  { slug: "googledrive", name: "Google Drive" },
  { slug: "gmail", name: "Gmail" },
  { slug: "googledocs", name: "Google Docs" },
  { slug: "googlecalendar", name: "Google Calendar" },
  { slug: "googlemaps", name: "Google Maps" },
  { slug: "cloudflare", name: "Cloudflare" },
  { slug: "vercel", name: "Vercel" },
  { slug: "digitalocean", name: "DigitalOcean" },
  { slug: "amazonaws", name: "AWS" },
  { slug: "python", name: "Python" },
  { slug: "npmjs", name: "npm" },
  { slug: "docker", name: "Docker" },
  { slug: "plex", name: "Plex" },
  { slug: "sonarr", name: "Sonarr" },
  { slug: "radarr", name: "Radarr" },
  { slug: "jellyfin", name: "Jellyfin" },
  { slug: "pihole", name: "Pi-hole" },
  { slug: "portainer", name: "Portainer" },
  { slug: "proxmox", name: "Proxmox" },
  { slug: "traefikproxy", name: "Traefik" },
  { slug: "nextcloud", name: "Nextcloud" },
  { slug: "homeassistant", name: "Home Assistant" },
  { slug: "grafana", name: "Grafana" },
  { slug: "prometheus", name: "Prometheus" },
  { slug: "jira", name: "Jira" },
  { slug: "confluence", name: "Confluence" },
  { slug: "linear", name: "Linear" },
  { slug: "railway", name: "Railway" },
  { slug: "supabase", name: "Supabase" },
  { slug: "stripe", name: "Stripe" },
  { slug: "paypal", name: "PayPal" },
  { slug: "steam", name: "Steam" },
  { slug: "twitch", name: "Twitch" },
  { slug: "tiktok", name: "TikTok" },
  { slug: "whatsapp", name: "WhatsApp" },
  { slug: "telegram", name: "Telegram" },
  { slug: "signal", name: "Signal" },
  { slug: "mozilla", name: "Mozilla" },
  { slug: "firefox", name: "Firefox" },
  { slug: "chromium", name: "Chromium" },
  { slug: "linux", name: "Linux" },
  { slug: "ubuntu", name: "Ubuntu" },
  { slug: "debian", name: "Debian" },
  { slug: "archlinux", name: "Arch Linux" },
  { slug: "raspberrypi", name: "Raspberry Pi" },
  { slug: "arduino", name: "Arduino" },
  { slug: "oculus", name: "Meta Quest" },
  { slug: "nintendoswitch", name: "Nintendo Switch" },
  { slug: "playstation", name: "PlayStation" },
  { slug: "xbox", name: "Xbox" },
  { slug: "wordpress", name: "WordPress" },
  { slug: "ghost", name: "Ghost" },
  { slug: "hugo", name: "Hugo" },
  { slug: "react", name: "React" },
  { slug: "vuedotjs", name: "Vue.js" },
  { slug: "nextdotjs", name: "Next.js" },
  { slug: "typescript", name: "TypeScript" },
  { slug: "rust", name: "Rust" },
  { slug: "go", name: "Go" },
  { slug: "nodejs", name: "Node.js" },
  { slug: "deno", name: "Deno" },
  { slug: "bun", name: "Bun" },
  { slug: "tailwindcss", name: "Tailwind CSS" },
  { slug: "prisma", name: "Prisma" },
  { slug: "postman", name: "Postman" },
  { slug: "visualstudiocode", name: "VS Code" },
  { slug: "jetbrains", name: "JetBrains" },
  { slug: "obsidian", name: "Obsidian" },
  { slug: "todoist", name: "Todoist" },
  { slug: "1password", name: "1Password" },
  { slug: "bitwarden", name: "Bitwarden" },
];

export function searchIcons(query: string): Array<{ slug: string; name: string }> {
  if (!query.trim()) return SEARCHABLE_ICONS.slice(0, 20);
  const q = query.toLowerCase();
  return SEARCHABLE_ICONS.filter(
    (icon) => icon.name.toLowerCase().includes(q) || icon.slug.toLowerCase().includes(q)
  );
}
