services:
  wayfinder:
    image: ghcr.io/calendar0917/wayfinder:latest
    container_name: wayfinder
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env.local
    pid: host
    restart: unless-stopped
